name: Maven CI

on:
  push:
    branches:
      - main  # Runs on every push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Maven Clean
        run: mvn clean

      - name: Run Unit Tests
        run: mvn test
